### ISSUE TITLE
运行返回python错误

### ISSUE THREAD

**Issue by Zhuangmoumou** [ikunshare/Onekey#1]
Traceback (most recent call last):
  File "main.py", line 59, in <module>
  File "main.py", line 54, in load_config
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 94 (char 93)
[1500] Failed to execute script 'main' due to unhandled exception!

**Comment by ikun0014** [comment]
json解码失败，无效的反斜杠，建议看运行路径是不是有什么问题，或者换最新发布
